[Variables]
showGpuName=0
showMemoryClock=0
showMemoryController=0
showVideoClock=0
showCoreVoltage=0
showLineGraph=0
showTempGraph=1

gpuName=""

useManualMaxVram=0
maxVram=3000
useMoboFanSensor=0

dualGpuMode=0

colorCoreUsage=255,246,42
colorMemoryUsage=107,198,250
colorFanUsage=107,238,98
colorMemoryController=255,204,0
colorTempGraph=200,0,0

; ====== DEFAULTS ======

dColorCoreUsage=255,246,42
dColorMemoryUsage=107,198,250
dColorFanUsage=107,238,98
dColorMemoryController=255,204,0
=the fox
